name: Deploy static content to Academis

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v1

    - name: build static html
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        make html

    - name: copy to academis server 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ACADEMIS_HOST }}
        username: ${{ secrets.ACADEMIS_USERNAME }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: _build/html/*
        target: /www/academis/pandas_go_to_space
        rm: true
        strip_components: 2
